### ISSUE TITLE
Promscale extension rpm

### ISSUE THREAD

**Issue by nikhil-postgres** [timescale/promscale_extension#24]
Hello,

We are trying promscale with promscale_extension, while promscale installation was straightforward, do we have an rpm for promscale_extension as well?. The current process of installation mentioned in README is complex. There are multiple dependencies prior to the installation of extension

**Comment by nikhil-postgres** [comment]
To add, We are not able to install cargo-pgx. Does it require internet connection? If yes, how do we install cargo-pgx in offline mode?

```
cargo install  cargo-pgx
    Updating crates.io index

warning: spurious network error (2 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)

```

**Comment by jgpruitt** [comment]
At the moment, we do not build and publish binaries or packages; we only support build from source. There has been talk about doing this -- it is something we recognize is needed -- but we aren't working on it at the moment AFAIK.

Having said that, it looks like there is a way to have cargo install from the filesystem rather than the internet with the `--path` option. It might be a bit painful, but I think you could download the dependencies separately and then copy to the target machine and run `cargo install` against them.

I *believe the `.lock` file will tell you all the packages that need to be installed. https://github.com/timescale/promscale_extension/blob/master/Cargo.lock

https://doc.rust-lang.org/cargo/commands/cargo-install.html

**Comment by JamesGuthrie** [comment]
I'm going to close this issue for now. We have released an rpm for the most recent version of the extension.
