### ISSUE TITLE
Creating extension without pre-creating the timescaledb extension breaks background jobs

### ISSUE THREAD

**Issue by cevian** [timescale/promscale_extension#514]
From https://timescaledb.slack.com/archives/C011FC0PPC5/p1663352149346699
```
Figured it out! I was running CREATE EXTENSION promscale;, of course, which seems to implicitly run CREATE EXTENSION timescaledb; but only partially. I changed it to run CREATE EXTENSION timescaledb; CREATE EXTENSION promscale; instead and now the jobs exist.
```

Must be our old logic for handling cases where there is no timescaledb installed is causing issues. We should fix and add a test for this install method to be supported

**Comment by JamesGuthrie** [comment]
I'm not sure what we should do to fix this. As I understand it, the issue is that the user manually ran `CREATE EXTENSION promscale;`, without first running `CREATE EXTENSION timescaledb;`. In that case, Promscale happily initialises itself as though no timescaledb is present (which is isn't), meaning that it also doesn't attempt to install the jobs (because it can't).

**Comment by jgpruitt** [comment]
Just spitballing here:
We could check to see whether the timescaledb extension is available and abort install if it is available but not installed. Kinda heavy handed, but likely what the user intended in most cases
This would break a bunch of our e2e tests though.

**Comment by cevian** [comment]
can we use `requires` in the extension [control file](https://www.postgresql.org/docs/current/extend-extensions.html)?

**Comment by jgpruitt** [comment]
Do we still support running without timescaledb? I thought we dropped that, but I believe we still have tests for it running on the connector side

**Comment by shivjm** [comment]
Shiv from Slack here.

> I'm not sure what we should do to fix this. As I understand it, the issue is that the user manually ran CREATE EXTENSION promscale;, without first running CREATE EXTENSION timescaledb;. In that case, Promscale happily initialises itself as though no timescaledb is present (which is isn't), meaning that it also doesn't attempt to install the jobs (because it can't).

For some context, I’m experimenting a lot as I put together an observability stack for myself, because my desired configuration is fairly non-standard. Everything else worked fine without the `CREATE EXTENSION timescaledb`; I didn’t know at the time that the jobs should exist in the first place, so I took this to mean I could safely omit it. I had no trouble using the database with Prometheus & Grafana that way. It was only when I was ready to configure retention and compression that I realized I was missing parts of the installation, and since [the jobs are described as being part of Promscale](https://docs.timescale.com/promscale/latest/manage-data/maintenance-jobs/), I thought the issue lay there until I tried installing the TimescaleDB extension first on a hunch.

**Comment by JamesGuthrie** [comment]
> Do we still support running without timescaledb?

We haven't officially dropped it yet, but we've been threatening to do it for a while 😅

**Comment by jgpruitt** [comment]
If we used the extension control file, it would have to be mandatory.

**Comment by JamesGuthrie** [comment]
We've fixed this issue by making the timescaledb extension a prerequisite for installing the promscale extension. This is a bit of a heavy-handed change, but we think that it is the right choice.

We believe that most users want to use Promscale with TimescaleDB, because otherwise features like compression are not available, and the overall experience of working with observability data is just not as good.

The maintenance and testing burden for maintaining the "with TimescaleDB" and "without TimescaleDB" use-cases doesn't seem to be proportional to the usage and utility of Promscale with TimescaleDB.
