### ISSUE TITLE
Provide OS packages for extension version 0.3.0

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#60]
We would like to have installable packages of the extension for the already-released 0.3.0. Ideally covering the same OS's as timescaledb does.

**Comment by bitwalker** [comment]
I've uploaded packages for Debian 11 and CentOS 7, for PostgreSQL 12-14 to the GitHub release for 0.3.0. If we wish to add more packages, I've saved my backport of the packaging scripts so that I can generate other packages as desired.

**Comment by cevian** [comment]
@bitwalker why centos 7 and not 8? Which RHEL versions does 7 support? Also do the Debian packages support ubuntu or would that be a separate package?

**Comment by JamesGuthrie** [comment]
I was able to install the debian packages on 20.04. I didn't do a full test with starting up the DB as well though.

**Comment by bitwalker** [comment]
@cevian CentOS 8 is EOL (it's deprecated in favor of the new streaming release format that Fedora uses, rather than tracking RHEL like it used to). CentOS 7 is the LTS and is far more common in the wild than CentOS 8. In any case, I suspect the .rpm works on both 7 and 8, though we should test to validate that (we don't declare any deps on packages that aren't available in one or the other, and the locations are stable between 7 and 8 AFAIK).

As far as sharing .deb packages built for Debian on Ubuntu, those should also work for the same reasons, and @JamesGuthrie test seems to confirm this. Building distro-specific packages is only really necessary when you are relying on things that are subtly different between them, but that isn't the case with our package.

**Comment by JamesGuthrie** [comment]
I tested the installation with the following combos. I was able to start the docker container and then run promscale in `startup.only` mode, which tests the timescaledb and promscale extensions (at least the installation thereof).

```
pg12-debian-9
pg13-debian-9
pg14-debian-9
pg12-debian-10
pg13-debian-10
pg14-debian-10
pg12-debian-11
pg13-debian-11
pg14-debian-11
pg12-ubuntu-18.04
pg13-ubuntu-18.04
pg14-ubuntu-18.04
pg12-ubuntu-20.04
pg13-ubuntu-20.04
pg14-ubuntu-20.04
pg12-ubuntu-21.04
pg13-ubuntu-21.04
pg14-ubuntu-21.04
```
