### ISSUE TITLE
Vulnerable versions of libexpat

### ISSUE THREAD

**Issue by florinpopescu** [timescale/promscale_extension#71]
Docker images use vulnerable versions of libexpat via Python3 XML processing modules (https://docs.python.org/3.9/library/xml.html#xml-vulnerabilities)

To be safe, libexpat pkg should be updated to v2.4.3 (https://github.com/libexpat/libexpat/blob/R_2_4_3/expat/Changes)

**Comment by JamesGuthrie** [comment]
@florinpopescu I assume that you're talking about the `timescale/timescaledb-docker-ha` docker image. The repository for that image is at https://github.com/timescale/timescaledb-docker-ha. I've opened an issue against that repo, but it doesn't look like there's a "quick fix" for now, because Ubuntu hasn't released patched versions of the package for any current releases.
